### ISSUE TITLE
Remove rust-toolchain file

### ISSUE THREAD

**Issue by Shemnei** [michidk/vulkan-engine#1]
Remove rust-toolchain file when error with `vk_mem 0.2.2` is solved.

**Comment by michidk** [comment]
We can remove as soon as all `#![feature...` attributes are marked as stable. We don't need that specific version anymore, since I upgraded vk_mem to 0.3.3 by using the git repo directly. We should remove the git repo again, as soon as an official release is available on creates registry.

**Comment by michidk** [comment]
Let's just stay on nightly for now.
